In [46]:
import pandas as pd

p_102= pd.read_csv('各鄉鎮市區人口密度/102.csv')
p_103= pd.read_csv('各鄉鎮市區人口密度/103.csv')
p_104= pd.read_csv('各鄉鎮市區人口密度/104.csv')
p_105= pd.read_csv('各鄉鎮市區人口密度/105.csv')
p_106= pd.read_csv('各鄉鎮市區人口密度/106.csv')
p_107= pd.read_csv('各鄉鎮市區人口密度/107.csv')
p_108= pd.read_csv('各鄉鎮市區人口密度/108.csv')
p_109= pd.read_csv('各鄉鎮市區人口密度/109.csv')
p_110= pd.read_csv('各鄉鎮市區人口密度/110.csv')
p_111= pd.read_csv('各鄉鎮市區人口密度/111.csv')
p_112= pd.read_csv('各鄉鎮市區人口密度/112.csv')

df1=pd.concat([p_102,p_103,p_104,p_105,p_106,p_107,p_108,p_109,p_110,p_111,p_112])

df2 = df1.rename(columns={'statistic_yyy':'統計年',
                    'site_id':'區域別',
                    'people_total':'年底人口數',
                    'area':'土地面積',
                    'population_density':'人口密度'})

df3 = df2.drop(index=0)
df3

,統計年,區域別,年底人口數,土地面積,人口密度
1,102,新北市板橋區,556920,23.1373,24070
2,102,新北市三重區,389813,16.317,23890
3,102,新北市中和區,415742,20.144,20639
4,102,新北市永和區,229062,5.7138,40089
5,102,新北市新莊區,409760,19.7383,20760
...,...,...,...,...,...
370,112,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [47]:
df4=df3.dropna()
df4

     統計年      區域別   年底人口數     土地面積   人口密度
1    102  新北市板橋區　  556920  23.1373  24070
2    102  新北市三重區　  389813   16.317  23890
3    102  新北市中和區　  415742   20.144  20639
4    102  新北市永和區　  229062   5.7138  40089
5    102  新北市新莊區　  409760  19.7383  20760
..   ...      ...     ...      ...    ...
366  112   連江縣北竿鄉    3136   9.9000    317
367  112   連江縣莒光鄉    1504   4.7000    320
368  112   連江縣東引鄉    1572   3.8000    414
369  112     東沙群島      …    2.3800     …
370  112     南沙群島      …    0.5045     …

[4070 rows x 5 columns]

In [49]:
df5 = df4.set_index('區域別')
df5

         統計年   年底人口數     土地面積   人口密度
區域別
新北市板橋區　  102  556920  23.1373  24070
新北市三重區　  102  389813   16.317  23890
新北市中和區　  102  415742   20.144  20639
新北市永和區　  102  229062   5.7138  40089
新北市新莊區　  102  409760  19.7383  20760
...      ...     ...      ...    ...
連江縣北竿鄉   112    3136   9.9000    317
連江縣莒光鄉   112    1504   4.7000    320
連江縣東引鄉   112    1572   3.8000    414
東沙群島     112      …    2.3800     …
南沙群島     112      …    0.5045     …

[4070 rows x 4 columns]

In [50]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4070 entries, 新北市板橋區　 to 南沙群島
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     4070 non-null   object
 1   年底人口數   4070 non-null   object
 2   土地面積    4070 non-null   object
 3   人口密度    4070 non-null   object
dtypes: object(4)
memory usage: 159.0+ KB

In [51]:
df5['土地面積'] = df5['土地面積'].astype(float)

In [52]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4070 entries, 新北市板橋區　 to 南沙群島
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     4070 non-null   object
 1   年底人口數   4070 non-null   object
 2   土地面積    4070 non-null   float64
 3   人口密度    4070 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.0+ KB

In [53]:
def to_int(value):
    try:
        return int(value)
    except:
        return 0

df5['年度人口數'] = df5['年底人口數'].map(to_int)
df5['人口密度'] = df5['人口密度'].map(to_int)

In [54]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4070 entries, 新北市板橋區　 to 南沙群島
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     4070 non-null   object
 1   年底人口數   4070 non-null   object
 2   土地面積    4070 non-null   float64
 3   人口密度    4070 non-null   int64
 4   年度人口數   4070 non-null   int64
dtypes: float64(1), int64(2), object(2)
memory usage: 190.8+ KB

In [55]:
df5

         統計年   年底人口數     土地面積   人口密度   年度人口數
區域別
新北市板橋區　  102  556920  23.1373  24070  556920
新北市三重區　  102  389813  16.3170  23890  389813
新北市中和區　  102  415742  20.1440  20639  415742
新北市永和區　  102  229062   5.7138  40089  229062
新北市新莊區　  102  409760  19.7383  20760  409760
...      ...     ...      ...    ...     ...
連江縣北竿鄉   112    3136   9.9000    317    3136
連江縣莒光鄉   112    1504   4.7000    320    1504
連江縣東引鄉   112    1572   3.8000    414    1572
東沙群島     112      …    2.3800      0       0
南沙群島     112      …    0.5045      0       0

[4070 rows x 5 columns]