In [12]:
import pandas as pd

df1 = pd.read_csv('上市公司資料.csv')
df1

,出表日期,資料年月,公司代號,公司名稱,產業別,營業收入-當月營收,營業收入-上月營收,營業收入-去年當月營收,營業收入-上月比較增減(%),營業收入-去年同月增減(%),累計營業收入-當月累計營收,累計營業收入-去年累計營收,累計營業收入-前期比較增減(%),備註
0,1110912,11108,1102,亞泥,水泥工業,7069221,7864622,7193266,-10.113658,-1.724460,59102719,54657145,8.133564,-
1,1110912,11108,1108,幸福,水泥工業,390053,326691,249977,19.395086,56.035555,2599544,2635052,-1.347526,去年同期本公司石材減產，致本月與去年同期相較增加50%以上。
2,1110912,11108,1109,信大,水泥工業,478276,557403,591358,-14.195654,-19.122427,4040555,4781224,-15.491201,-
3,1110912,11108,1110,東泥,水泥工業,176935,134470,109276,31.579534,61.915700,1073546,1203643,-10.808604,主要係母公司東南水泥股份有限公司以及子公司東南高良資源再生股份有限公司銷貨收入較去年同期增加
4,1110912,11108,1213,大飲,食品工業,38696,29503,42312,31.159543,-8.546039,266205,299920,-11.241331,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,1110912,11108,9942,茂順,其他,352730,349111,336002,1.036633,4.978542,2601215,2512658,3.524435,-
835,1110912,11108,9943,好樂迪,觀光事業,212912,197756,5090,7.663990,4082.946955,1465862,1062550,37.956990,110年5月15日起配合防疫政策，暫停營業
836,1110912,11108,9944,新麗,其他,179660,231139,178668,-22.271880,0.555220,1877352,1848775,1.545726,-
837,1110912,11108,9955,佳龍,其他,81881,85625,109319,-4.372555,-25.099022,826811,994253,-16.840985,-
838,1110912,11108,9958,世紀鋼,鋼鐵工業,757968,651699,1073536,16.306454,-29.395195,5374177,6195141,-13.251740,-

In [29]:
import pandas as pd

df1 = pd.read_csv('上市公司資料.csv')

df2 = df1.drop(index=0,)

In [30]:
df3=df2.drop(columns=['出表日期','資料年月','營業收入-上月比較增減(%)','營業收入-去年同月增減(%)','營業收入-去年當月營收'
                      ,'累計營業收入-當月累計營收','累計營業收入-前期比較增減(%)','備註','累計營業收入-去年累計營收'])
df3

     公司代號 公司名稱   產業別  營業收入-當月營收  營業收入-上月營收
1    1108   幸福  水泥工業     390053     326691
2    1109   信大  水泥工業     478276     557403
3    1110   東泥  水泥工業     176935     134470
4    1213   大飲  食品工業      38696      29503
5    1215   卜蜂  食品工業    2393814    2400161
..    ...  ...   ...        ...        ...
834  9942   茂順    其他     352730     349111
835  9943  好樂迪  觀光事業     212912     197756
836  9944   新麗    其他     179660     231139
837  9955   佳龍    其他      81881      85625
838  9958  世紀鋼  鋼鐵工業     757968     651699

[838 rows x 5 columns]

In [31]:
df4=df3.set_index('公司代號')
df4

     公司名稱   產業別  營業收入-當月營收  營業收入-上月營收
公司代號
1108   幸福  水泥工業     390053     326691
1109   信大  水泥工業     478276     557403
1110   東泥  水泥工業     176935     134470
1213   大飲  食品工業      38696      29503
1215   卜蜂  食品工業    2393814    2400161
...   ...   ...        ...        ...
9942   茂順    其他     352730     349111
9943  好樂迪  觀光事業     212912     197756
9944   新麗    其他     179660     231139
9955   佳龍    其他      81881      85625
9958  世紀鋼  鋼鐵工業     757968     651699

[838 rows x 4 columns]

In [33]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, 1108 to 9958
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   公司名稱       838 non-null    object
 1   產業別        838 non-null    object
 2   營業收入-當月營收  838 non-null    int64
 3   營業收入-上月營收  838 non-null    int64
dtypes: int64(2), object(2)
memory usage: 32.7+ KB

In [38]:
df4['公司代號'] = df4['公司代號'].astype(str)
nums = []
for num in df4['公司代號']:
    try:
        nums.append(str(num))
    except:
        nums.append(0)

KeyError: '公司代號'